In [1]:
import pandas as pd
import numpy as np
from sklearn import preprocessing
import matplotlib.pyplot as plt 
#plt.rc("font", size=14)
from sklearn.linear_model import LogisticRegression
import seaborn as sns
%matplotlib inline

In [2]:
#Import data
data=pd.read_csv('diabetes.csv')

In [3]:
data.columns

Index(['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin',
       'BMI', 'DiabetesPedigreeFunction', 'Age', 'Outcome'],
      dtype='object')

In [4]:
data.shape

(768, 9)

In [5]:
data.describe(include='all')

Pregnancies     Glucose  BloodPressure  SkinThickness     Insulin  \
count   768.000000  768.000000     768.000000     768.000000  768.000000   
mean      3.845052  120.894531      69.105469      20.536458   79.799479   
std       3.369578   31.972618      19.355807      15.952218  115.244002   
min       0.000000    0.000000       0.000000       0.000000    0.000000   
25%       1.000000   99.000000      62.000000       0.000000    0.000000   
50%       3.000000  117.000000      72.000000      23.000000   30.500000   
75%       6.000000  140.250000      80.000000      32.000000  127.250000   
max      17.000000  199.000000     122.000000      99.000000  846.000000   

              BMI  DiabetesPedigreeFunction         Age     Outcome  
count  768.000000                768.000000  768.000000  768.000000  
mean    31.992578                  0.471876   33.240885    0.348958  
std      7.884160                  0.331329   11.760232    0.476951  
min      0.000000                  0.078000   21.000000    0.000000  
25%     27.300000                  0.243750   24.000000    0.000000  
50%     32.000000                  0.372500   29.000000    0.000000  
75%     36.600000                  0.626250   41.000000    1.000000  
max     67.100000                  2.420000   81.000000    1.000000

In [6]:
data.corr(method='spearman')

Pregnancies   Glucose  BloodPressure  SkinThickness  \
Pregnancies                  1.000000  0.130734       0.185127      -0.085222   
Glucose                      0.130734  1.000000       0.235191       0.060022   
BloodPressure                0.185127  0.235191       1.000000       0.126486   
SkinThickness               -0.085222  0.060022       0.126486       1.000000   
Insulin                     -0.126723  0.213206      -0.006771       0.541000   
BMI                          0.000132  0.231141       0.292870       0.443615   
DiabetesPedigreeFunction    -0.043242  0.091293       0.030046       0.180390   
Age                          0.607216  0.285045       0.350895      -0.066795   
Outcome                      0.198689  0.475776       0.142921       0.089728   

                           Insulin       BMI  DiabetesPedigreeFunction  \
Pregnancies              -0.126723  0.000132                 -0.043242   
Glucose                   0.213206  0.231141                  0.091293   
BloodPressure            -0.006771  0.292870                  0.030046   
SkinThickness             0.541000  0.443615                  0.180390   
Insulin                   1.000000  0.192726                  0.221150   
BMI                       0.192726  1.000000                  0.141192   
DiabetesPedigreeFunction  0.221150  0.141192                  1.000000   
Age                      -0.114213  0.131186                  0.042909   
Outcome                   0.066472  0.309707                  0.175353   

                               Age   Outcome  
Pregnancies               0.607216  0.198689  
Glucose                   0.285045  0.475776  
BloodPressure             0.350895  0.142921  
SkinThickness            -0.066795  0.089728  
Insulin                  -0.114213  0.066472  
BMI                       0.131186  0.309707  
DiabetesPedigreeFunction  0.042909  0.175353  
Age                       1.000000  0.309040  
Outcome                   0.309040  1.000000

In [7]:
feature_cols = ['Glucose','BMI','Age','Pregnancies','DiabetesPedigreeFunction','BloodPressure','SkinThickness','Insulin']
X = data[feature_cols] # Features
y = data.Outcome # Target variable

In [8]:
# split X and y into training and testing sets
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.25,random_state=30)

In [9]:
# import the class
from sklearn.linear_model import LogisticRegression

# instantiate the model (using the default parameters)
model = LogisticRegression(max_iter=500)

In [10]:
model

LogisticRegression(max_iter=500)

In [11]:
from sklearn.model_selection import cross_val_score  
all_accuracies = cross_val_score(estimator=model, X=X_train, y=y_train, cv=5)

In [12]:
all_accuracies

array([0.77586207, 0.75652174, 0.7826087 , 0.73913043, 0.76521739])

In [13]:
# import the class
from sklearn.linear_model import LogisticRegression

# instantiate the model (using the default parameters)
#model = LogisticRegression()

# fit the model with data
model.fit(X_train,y_train)

#Prediction
#y_pred=model.predict(X_test)

LogisticRegression(max_iter=500)

In [14]:
#model.predict(X_test)  # default threshold is 0.5
#If you want to change to 0.3
y_pred=(model.predict_proba(X_test)[:,1] >= 0.4)*1
y_pred

array([0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1,
       1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0,
       1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0,
       0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1])

In [15]:
from sklearn import metrics
metrics.roc_auc_score(y_test, y_pred)

0.7464019851116626

In [16]:
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))
print("Precision:",metrics.precision_score(y_test, y_pred))
print("Recall:",metrics.recall_score(y_test, y_pred))

Accuracy: 0.7708333333333334
Precision: 0.6363636363636364
Recall: 0.6774193548387096


In [17]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.84      0.82      0.83       130
           1       0.64      0.68      0.66        62

    accuracy                           0.77       192
   macro avg       0.74      0.75      0.74       192
weighted avg       0.78      0.77      0.77       192



In [19]:
loss=model.predict_proba(X_test)

In [20]:
loss

array([[0.87895868, 0.12104132],
       [0.85823865, 0.14176135],
       [0.85919399, 0.14080601],
       [0.37750873, 0.62249127],
       [0.83402917, 0.16597083],
       [0.95055431, 0.04944569],
       [0.27107424, 0.72892576],
       [0.75161562, 0.24838438],
       [0.65386225, 0.34613775],
       [0.95448749, 0.04551251],
       [0.90030021, 0.09969979],
       [0.81626829, 0.18373171],
       [0.87237575, 0.12762425],
       [0.80126346, 0.19873654],
       [0.92062003, 0.07937997],
       [0.92152848, 0.07847152],
       [0.79367405, 0.20632595],
       [0.80028161, 0.19971839],
       [0.18727743, 0.81272257],
       [0.85829283, 0.14170717],
       [0.57473318, 0.42526682],
       [0.11684733, 0.88315267],
       [0.51002064, 0.48997936],
       [0.64751255, 0.35248745],
       [0.03583846, 0.96416154],
       [0.55987038, 0.44012962],
       [0.90811765, 0.09188235],
       [0.95331711, 0.04668289],
       [0.95860295, 0.04139705],
       [0.64305647, 0.35694353],
       [0.

In [22]:
print(model.rsquared_adj)

AttributeError: 'LogisticRegression' object has no attribute 'rsquared_adj'